pipelines:
  branches:
    main:
      - step:
          name: Deploy to Shopify
          image: node:20.17.0
          caches:
            - node
          script:
            - npm install -g @shopify/cli
            - shopify theme pull --store=$SHOPIFY_STORE --password=$SHOPIFY_PASSWORD --themeid=$SHOPIFY_THEME_ID
            - shopify theme push --store=$SHOPIFY_STORE --password=$SHOPIFY_PASSWORD --themeid=$SHOPIFY_THEME_ID
